version: '3.8'

services:
  web:
    image: ngnix:latest
    container_name: website
    volumes:
      - /var/www/website/public:/usr/share/ngnix/html
    ports:
      - "8080:80"
    restart: always
